### ISSUE TITLE
Fix Continuous Integration

### ISSUE THREAD

**Issue by JonathanRufino** [NotifiCar/NotifiCar#20]

**Comment by JonathanRufino** [comment]
Android is working now. See [# Update fastlane configuration to deploy to playstore](https://github.com/NotifiCar/NotifiCar/commit/328944843d058f473e9491681a7c9f2a21b16564)

**Comment by luishng** [comment]
IOs is working now. See [# Fix ios Podfile](https://github.com/NotifiCar/NotifiCar/commit/c10800e24a0e09be7ef88af2c48fdc8fb3363ddf)
